-- Close anonymous INSERT on public.messages, and write down the policies.
--
-- ---------------------------------------------------------------------------
-- A correction, kept deliberately.
--
-- The first draft of this file recreated every policy from scratch, on the
-- assumption that a black-box probe of the REST API had shown what they were.
-- Reading pg_policies before applying it showed that assumption was wrong three
-- times over, and that running it would have made this database materially less
-- safe than it already was:
--
--   1. Admin writes are gated on is_admin(), an allowlist keyed to the email in
--      the JWT. The draft would have replaced that with `using (true)` for the
--      authenticated role, so ANY signed-in Supabase user could have rewritten
--      every table on the site.
--   2. chat_usage deliberately carries no policies at all. RLS is on, so that
--      denies every client role while the service role still bypasses it. The
--      draft would have ADDED a read policy for authenticated users, exposing
--      the visitor IP ledger it was supposed to protect.
--   3. messages has four narrow policies. Collapsing them into one FOR ALL
--      policy would have opened the contact inbox to any authenticated user.
--
-- It would also have failed at its actual purpose: the live policy is named
-- "messages anon insert", with spaces, so `drop policy if exists
-- messages_anon_insert` matches nothing and the insert would have survived.
-- Permissive policies OR together, so the result would have been the old policy
-- and a wider new one, both in force.
--
-- The lesson is the point of the comment: probing an API from outside shows you
-- behaviour, not policy. Read the catalogue before rewriting authorisation.
-- ---------------------------------------------------------------------------
--
-- The policies as they actually stand, verified against pg_policies on
-- 2026-09-03. Everything below is left exactly as it is:
--
--   profile, experience, automations
--     "<table> public read"   SELECT  anon, authenticated  using (true)
--     "<table> admin write"   ALL     authenticated        using/check is_admin()
--
--   posts, projects
--     "<table> public read"   SELECT  anon, authenticated  using (published)
--     "<table> admin write"   ALL     authenticated        using/check is_admin()
--
--   messages
--     "messages admin read"   SELECT  authenticated        using (is_admin())
--     "messages admin update" UPDATE  authenticated        using/check is_admin()
--     "messages admin delete" DELETE  authenticated        using (is_admin())
--     "messages anon insert"  INSERT  anon, authenticated  check (true)   <- dropped
--
--   chat_usage, admins
--     RLS enabled, no policies: denied to every client role, service role only.
--
-- The single change is the last line of the messages block.
--
-- Why: the contact handler used to write as the visitor, so anonymous INSERT
-- had to be open — and that meant the Supabase REST endpoint accepted rows
-- directly, making the honeypot, the length caps, the address validation and
-- the notification throttle all optional for anyone who skipped the form and
-- posted at the API instead. The handler now writes with the service role,
-- which bypasses RLS, so the policy can go and every write has to come through
-- the checks. That application change is already deployed and verified live,
-- so this is safe to run now.

begin;

drop policy if exists "messages anon insert" on public.messages;

commit;
